version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always